config/routes.rb
Vish::Application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth_callbacks', registrations: 'registrations'}

  resource :session_locale
  resource :spam_report

  resources :quiz_sessions do
    get "results", :on => :member
  end
  match 'quiz_sessions/:id/close' => 'quiz_sessions#close'
  match 'quiz_sessions/:id/delete' => 'quiz_sessions#delete'
  match 'quiz_sessions/:id/answer' => 'quiz_sessions#updateAnswers'
  match 'qs/:id' => 'quiz_sessions#show'

  match 'help' => 'help#index'
  match 'faq' => 'faq#index'
  match 'legal_notice' => 'legal_notice#index'
  match 'overview' => 'overview#index'
  
  match 'users/:id/excursions' => 'users#excursions'
  match 'users/:id/resources' => 'users#resources'
  match 'users/:id/events' => 'users#events'
  match 'users/:id/categories' => 'users#categories'
  match 'users/:id/followers' => 'users#followers'
  match 'users/:id/followings' => 'users#followings'

  match '/apis/search' => 'federated_search#search'
  match '/apis/iframe_api' => 'excursions#iframe_api'
  match '/apis/recommender' => 'recommender#api_excursion_suggestions'

  match '/excursions/thumbnails' => 'excursions#excursion_thumbnails'
  match '/excursion_thumbnails' => 'excursions#excursion_thumbnails'

  match 'excursions/last_slide' => 'excursions#last_slide'
  match 'excursions/preview' => 'excursions#preview'
 
  match 'excursions/:id/metadata' => 'excursions#metadata'
  match 'excursions/:id/scormMetadata' => 'excursions#scormMetadata'
  match 'excursions/:id/clone' => 'excursions#clone'
  match '/excursions/:id/evaluate' => 'excursions#evaluate'
  match '/excursions/:id/learning_evaluate' => 'excursions#learning_evaluate'
  
  match '/excursions/:id.mashme' => 'excursions#show', :defaults => { :format => "gateway", :gateway => 'mashme' }
  match '/excursions/:id.embed' => 'excursions#show', :defaults => { :format => "full" }

  match '/excursions/tmpJson' => 'excursions#uploadTmpJSON', :via => :post
  match '/excursions/tmpJson' => 'excursions#downloadTmpJSON', :via => :get

  match '/categories/add_items' => 'categories#add_items', :via => :post
  match '/categories/favorites' => 'categories#show_favorites'

  match 'resources/search' => 'resources#search'
  
  match 'lre/search' => 'lre#search_lre'

  match '/home.json' => 'home#index', :format => :json

  match '/home' => 'excursions#index'

  resources :pdfexes

  match 'user_manual' => 'help#download_user_manual'

  resources :competitions
  resource :contest
  resources :contest_all
  resources :about

  match '/catalogue' => 'catalogue#index'
  match '/catalogue/:category' => 'catalogue#show'

  match '/s/:id' => "shortener/shortened_urls#show"

  mount OaiRepository::Engine => "/oai_repository"

  namespace :loep do
    resources :los
  end

  resources :tracking_system_entries

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SocialStream::Controllers::Subjects

  load_and_authorize_resource :except => [:current]

  before_filter :authenticate_user!, only: :current

  respond_to :html, :xml, :js
  
  def index
    raise ActiveRecord::RecordNotFound
  end

  def show
    show! do |format|
      format.html{
        if !params[:page]
          render "show"
        else
          render :partial => "excursions/excursions_profile", :locals => {:scope => :me, :limit => 0, :page=> params[:page], :sort_by=> params[:sort_by]||"updated_at"}, :layout => false
        end
      }
    end
  end

  def excursions
    respond_to do |format|
      format.html{        
        render :partial => 'excursions/profile_excursions', :locals => {:scope => :me, :limit => 0, :page=> params[:page]||1, :sort_by=> params[:sort_by]||"updated_at"}, :layout => false
      }
    end
  end

  def resources
    respond_to do |format|
      format.html{        
        if !params[:page] || (params[:page] && (params[:page] == 1 || params[:page]==0))
          render :partial => 'repositories/profile_resources', :locals => {:scope => :me, :limit => 0, :page=> params[:page]||1, :sort_by=> params[:sort_by]||"updated_at"}, :layout => false
        else
          render :partial => 'repositories/resources', :locals => {:scope => :me, :limit => 0, :page=> params[:page], :sort_by=> params[:sort_by]||"updated_at"}, :layout => false
        end
      }
    end
  end

  def events
    respond_to do |format|
      format.html{       
        if !params[:page] || (params[:page] && (params[:page] == 1 || params[:page]==0)) 
          render :partial => 'events/profile_events', :locals => {:scope => :me, :limit => 0, :page=> params[:page]||1, :sort_by=> params[:sort_by]||"updated_at"}, :layout => false
        else
          render :partial => 'events/events', :locals => {:scope => :me, :limit => 0, :page=> params[:page], :sort_by=> params[:sort_by]||"updated_at"}, :layout => false
        end
      }
    end
  end

  def categories
    respond_to do |format|
      format.html{  
        if !params[:page] || (params[:page] && (params[:page] == 1 || params[:page]==0))
          render :partial => 'categories/profile_categories', :locals => {:scope => :me, :limit => 0, :page=> params[:page]||1, :sort_by=> params[:sort_by]||"updated_at"}, :layout => false
        else
          render :partial => 'categories/categories', :locals => {:scope => :me, :limit => 0, :page=> params[:page], :sort_by=> params[:sort_by]||"updated_at"}, :layout => false
        end
      }
    end
  end

  def followers
    respond_to do |format|
      format.html{        
        render partial: 'users/user', collection: profile_or_current_subject.followers, :layout => false
      }
    end
  end

  def followings
    respond_to do |format|
      format.html{        
        render partial: 'users/user', collection: profile_or_current_subject.followings.where(object_type: 'Actor').includes(:actor).map(&:actor), :layout => false
      }
    end
  end

  def current
    respond_to do |format|
      format.json { render json: current_user.to_json }
    end
  end

  # Supported through devise
  def new; end; def create; end
  # Not supported yet
  def destroy; end
end

app/views/users/order_by_dropdown/_events.html.erb
<div class="dropdown">  
  <% default_sort_by = profile_subject_is_current? ? "updated_at" : "popularity"%>
  <% icon = profile_subject_is_current? ? "pencil" : "dashboard"%>
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown">
    <i class="fa fa-<%=icon%>"></i> 
    <%=t('order_by.' + default_sort_by)%>
    <i class="fa fa-angle-down"></i>
  </button>
  <ul class="dropdown-menu dropdown-menu-left" role="menu" aria-labelledby="dLabel">
    <li>
      <a href="#" onclick="events_dropdown_select('popularity');" class="sort_by_selected" sort-by-key='popularity'> 
        <i class="fa fa-dashboard"></i>
        <%=t('order_by.popularity')%>
      </a>
    </li>
    <li>
      <a href="#" onclick="events_dropdown_select('updated_at');" sort-by-key='updated_at'>
        <i class="fa fa-pencil"></i>
        <%=t('order_by.updated_at')%>
      </a>
    </li>
    <li>
      <a href="#" onclick="events_dropdown_select('created_at');" sort-by-key='created_at'>
        <i class="fa fa-bolt"></i>
        <%=t('order_by.created_at')%>
      </a>
    </li>
    <li>
      <a href="#" onclick="events_dropdown_select('visits');" sort-by-key='visits'>
        <i class="fa fa-eye"></i> 
        <%=t('order_by.visits')%>
      </a>
    </li>
    <li>
      <a href="#" onclick="events_dropdown_select('favorites');" sort-by-key='favorites'>
        <i class="fa fa-star"></i> 
        <%=t('order_by.favorites')%>
      </a>
    </li>
  </ul>
</div>

<%= content_for :javascript do %>
 
  var param = "<%=params[:sort_by]%>";

  if(param && param!=""){
    var value = $("#order_by_selector_events .dropdown-menu [sort-by-key="+param+"]").html();
    $("#dropdownMenuOrdByevents").html(value + '<i class="icon-angle-down"></i>'); 
  }
  
<%end%>

<script>
var events_dropdown_select = function(option) {
  $("#events_tab_ready").html("");
  $('.loader_pagination').show();
  $.ajax({
      type : "GET",
      url : "<%= user_url(profile_subject) %>/events?sort_by=" + option,
      success : function(html) {
        $("#order_by_selector_events").attr("li_selected", option);     
        var value = $("#order_by_selector_events .dropdown-menu [sort-by-key="+option+"]").html();
        $("#dropdownMenuOrdByevents").html(value + '<i class="fa fa-angle-down"></i>');
        $('.loader_pagination').hide();      
        $("#events_tab_ready").replaceWith(html);
        re_apply_pageless("events");
      },
      error: function(){
        //console.log("error loading events");
     }
    });
}

</script>

app/views/users/order_by_dropdown/_excursions.html.erb
<div class="dropdown">
  <% default_sort_by = profile_subject_is_current? ? "updated_at" : "popularity"%>
  <% icon = profile_subject_is_current? ? "pencil" : "dashboard"%>
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu4" data-toggle="dropdown">
    <i class="fa fa-<%=icon%>"></i> 
    <%=t('order_by.'+ default_sort_by)%>
    <i class="fa fa-angle-down"></i>
  </button>
  <ul class="dropdown-menu dropdown-menu-left" role="menu" aria-labelledby="dLabel">
    <li>
      <a href="#" onclick="excursions_dropdown_select('popularity');" class="sort_by_selected" sort-by-key='popularity'> 
        <i class="fa fa-dashboard"></i>
        <%=t('order_by.popularity')%>
      </a>
    </li>
    <li>
      <a href="#" onclick="excursions_dropdown_select('updated_at');" sort-by-key='updated_at'>
        <i class="fa fa-pencil"></i>
        <%=t('order_by.updated_at')%>
      </a>
    </li>
    <li>
      <a href="#" onclick="excursions_dropdown_select('created_at');" sort-by-key='created_at'>
        <i class="fa fa-bolt"></i>
        <%=t('order_by.created_at')%>
      </a>
    </li>
    <li>
      <a href="#" onclick="excursions_dropdown_select('visits');" sort-by-key='visits'>
        <i class="fa fa-eye"></i> 
        <%=t('order_by.visits')%>
      </a>
    </li>
    <li>
      <a href="#" onclick="excursions_dropdown_select('favorites');" sort-by-key='favorites'>
        <i class="fa fa-star"></i> 
        <%=t('order_by.favorites')%>
      </a>
    </li>
  </ul>
</div>

<%= content_for :javascript do %>
 
  var param = "<%=params[:sort_by]%>";

  if(param && param!=""){
    var value = $("#order_by_selector_excursions .dropdown-menu [sort-by-key="+param+"]").html();
    $("#dropdownMenuOrdByExcursions").html(value + '<i class="icon-angle-down"></i>'); 
  }
  
<%end%>

<script>
var excursions_dropdown_select = function(option) {
  $("#excursions_tab_ready").html("");
  $('.loader_pagination').show();
  $.ajax({
      type : "GET",
      url : "<%= user_url(profile_subject) %>/excursions?sort_by=" + option,
      success : function(html) { 
        $("#order_by_selector_excursions").attr("li_selected", option);
        var value = $("#order_by_selector_excursions .dropdown-menu [sort-by-key="+option+"]").html();
        $("#dropdownMenuOrdByExcursions").html(value + '<i class="fa fa-angle-down"></i>');
        $('.loader_pagination').hide();      
        $("#excursions_tab_ready").replaceWith(html);
        re_apply_pageless("excursions");
      },
      error: function(){
        //console.log("error loading excursions");
     }
    });
}

</script>

app/views/users/order_by_dropdown/_resources.html.erb
<div class="dropdown">
  <% default_sort_by = profile_subject_is_current? ? "updated_at" : "popularity"%>
  <% icon = profile_subject_is_current? ? "pencil" : "dashboard"%>
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu4" data-toggle="dropdown">
    <i class="fa fa-<%=icon%>"></i> 
    <%=t('order_by.' + default_sort_by)%>
    <i class="fa fa-angle-down"></i>
  </button>
  <ul class="dropdown-menu dropdown-menu-left" role="menu" aria-labelledby="dLabel">
    <li>
      <a href="#" onclick="resources_dropdown_select('popularity');" class="sort_by_selected" sort-by-key='popularity'> 
        <i class="fa fa-dashboard"></i>
        <%=t('order_by.popularity')%>
      </a>
    </li>
    <li>
      <a href="#" onclick="resources_dropdown_select('updated_at');" sort-by-key='updated_at'>
        <i class="fa fa-pencil"></i>
        <%=t('order_by.updated_at')%>
      </a>
    </li>
    <li>
      <a href="#" onclick="resources_dropdown_select('created_at');" sort-by-key='created_at'>
        <i class="fa fa-bolt"></i>
        <%=t('order_by.created_at')%>
      </a>
    </li>
    <li>
      <a href="#" onclick="resources_dropdown_select('visits');" sort-by-key='visits'>
        <i class="fa fa-eye"></i> 
        <%=t('order_by.visits')%>
      </a>
    </li>
    <li>
      <a href="#" onclick="resources_dropdown_select('favorites');" sort-by-key='favorites'>
        <i class="fa fa-star"></i> 
        <%=t('order_by.favorites')%>
      </a>
    </li>
  </ul>
</div>

<%= content_for :javascript do %>
 
  var param = "<%=params[:sort_by]%>";

  if(param && param!=""){
    var value = $("#order_by_selector_resources .dropdown-menu [sort-by-key="+param+"]").html();
    $("#dropdownMenuOrdByresources").html(value + '<i class="icon-angle-down"></i>'); 
  }
  
<%end%>

<script>
var resources_dropdown_select = function(option) {
  $("#resources_tab_ready").html("");
  $('.loader_pagination').show();
  $.ajax({
      type : "GET",
      url : "<%= user_url(profile_subject) %>/resources?sort_by=" + option,
      success : function(html) {
        $("#order_by_selector_resources").attr("li_selected", option);
        var value = $("#order_by_selector_resources .dropdown-menu [sort-by-key="+option+"]").html();
        $("#dropdownMenuOrdByresources").html(value + '<i class="fa fa-angle-down"></i>');
        $('.loader_pagination').hide();      
        $("#resources_tab_ready").replaceWith(html);
        re_apply_pageless("resources");
      },
      error: function(){
        //console.log("error loading resources");
     }
    });
}

</script>