config/routes.rb
Vish::Application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth_callbacks', registrations: 'registrations'}

  resource :session_locale
  resource :spam_report

  resources :quiz_sessions do
    get "results", :on => :member
  end
  match 'quiz_sessions/:id/close' => 'quiz_sessions#close'
  match 'quiz_sessions/:id/delete' => 'quiz_sessions#delete'
  match 'quiz_sessions/:id/answer' => 'quiz_sessions#updateAnswers'
  match 'qs/:id' => 'quiz_sessions#show'

  match 'help' => 'help#index'
  match 'faq' => 'faq#index'
  match 'legal_notice' => 'legal_notice#index'
  match 'overview' => 'overview#index'
  
  match 'users/:id/excursions' => 'users#excursions'
  match 'users/:id/resources' => 'users#resources'
  match 'users/:id/events' => 'users#events'
  match 'users/:id/categories' => 'users#categories'
  match 'users/:id/followers' => 'users#followers'
  match 'users/:id/followings' => 'users#followings'

  match '/apis/search' => 'federated_search#search'
  match '/apis/iframe_api' => 'excursions#iframe_api'
  match '/apis/recommender' => 'recommender#api_excursion_suggestions'

  match '/excursions/thumbnails' => 'excursions#excursion_thumbnails'
  match '/excursion_thumbnails' => 'excursions#excursion_thumbnails'

  match 'excursions/last_slide' => 'excursions#last_slide'
  match 'excursions/preview' => 'excursions#preview'
 
  match 'excursions/:id/metadata' => 'excursions#metadata'
  match 'excursions/:id/scormMetadata' => 'excursions#scormMetadata'
  match 'excursions/:id/clone' => 'excursions#clone'
  match '/excursions/:id/evaluate' => 'excursions#evaluate'
  match '/excursions/:id/learning_evaluate' => 'excursions#learning_evaluate'
  
  match '/excursions/:id.mashme' => 'excursions#show', :defaults => { :format => "gateway", :gateway => 'mashme' }
  match '/excursions/:id.embed' => 'excursions#show', :defaults => { :format => "full" }

  match '/excursions/tmpJson' => 'excursions#uploadTmpJSON', :via => :post
  match '/excursions/tmpJson' => 'excursions#downloadTmpJSON', :via => :get

  match '/categories/add_items' => 'categories#add_items', :via => :post
  match '/categories/favorites' => 'categories#show_favorites'

  match 'resources/search' => 'resources#search'
  
  match 'lre/search' => 'lre#search_lre'

  match '/home.json' => 'home#index', :format => :json

  match '/home' => 'excursions#index'

  resources :pdfexes

  match 'user_manual' => 'help#download_user_manual'

  resources :competitions
  resource :contest
  resources :contest_all
  resources :about

  match '/catalogue' => 'catalogue#index'
  match '/catalogue/:category' => 'catalogue#show'

  match '/s/:id' => "shortener/shortened_urls#show"

  mount OaiRepository::Engine => "/oai_repository"

  namespace :loep do
    resources :los
  end

  resources :tracking_system_entries

end

app/models/category.rb
class Category < ActiveRecord::Base
  include SocialStream::Models::Object

  validates_presence_of :title
  validate :title_not_duplicated

  define_index do
    activity_object_index
  end

  private
  def title_not_duplicated
    errors.add(:title, "duplicated") unless Category.all.map{ |category| category.id if(category.owner_id == self.owner_id && category.title == self.title) }.compact.blank?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include SocialStream::Controllers::Objects

  #before_filter :add_item_to_categories, :only => [:create, :update]
  skip_load_and_authorize_resource :only => [:add_items]
  
  def show_favorites
    render "favorites"
  end

  def create
    create! do |success, failure|
      success.json { render :json => {"title"=>@category.title, "id"=>@category.id}, :status => 200 }
      #failure.json { render :json => {"errors" => @category.errors}, :status => 400}
      failure.json { render :json => {"errors" => @category.errors.full_messages.to_sentence}, :status => 400}
    end
  end

  def update
    update! do |format|
      format.json {render :json => { :success => true }}
    end
  end

  def add_items
    if params[:item_type].present? && params["categories_array"].present?
      cat_array = JSON.parse(params["categories_array"])
      #2 actions, remove categories that are no longer assinged and apply new ones
      item = params[:item_type].constantize.find(params[:item_id]).activity_object
      item.holder_categories.each do |cat|
        if cat_array.include?(cat.id)
          cat_array.delete(cat.id) #remove item because the category is already applied
          next
        end
        #the_cat = Category.find(cat.id)
        #the_cat.property_objects.delete(item)
      end
      #now apply the rest of categories, the new ones
      cat_array.each do |new_cat_id|
        new_cat = Category.find(new_cat_id)
        new_cat.property_objects << item
      end
      render :json => { :success => true }
    end
  end


  def destroy
    super do |format|
      format.html {
        redirect_to user_path(current_user)
       }

      format.js
    end
   end

  private

  def add_item_to_categories
    if params[:item_type].present?
      included = @category.property_objects.include? params[:item_type].constantize.find(params[:item_id]).activity_object
      if params[:insert]=="true" && !included
        @category.property_objects << params[:item_type].constantize.find(params[:item_id]).activity_object
      elsif params[:insert]=="false" && included
        #we remove it
        @category.property_objects.delete(params[:item_type].constantize.find(params[:item_id]).activity_object)
      end
      params.delete :item_type
      params.delete :item_id
    end
  end

  def allowed_params
    [:item_type, :item_id]
  end

end

app/views/categories/_categorie-add.html.erb
<li href="#AddCategory" data-toggle="modal" class="new-item">
<%= link_to image_tag("icons/add.svg"), "#" ,  :class=> "img-box" %>
  <div class="action-name">
    Add New Categorie  
  </div>
</li>

app/views/categories/_categorie.html.erb
<li class="box-item">

<!--IMG categories-->
  <%= link_to image_tag("items/cat-prev.png"), "#",  :class=> "img-box"  %>
<!--INFO categories-->
  <div class="info">
<!--Title -->
    <h5 class="name">
      <a>
        categorie name  
      </a>
    </h5>
<!--Autor -->
    <div class="author"> 
      <a>author name</a>   
    </div>
<!--____________________ -->
    <div class="info-bottom">
      <hr class="soften">
<!--like -->
      <div class="like">    
        <div class="count">32</div>
        <%= link_to image_tag("icons/likes/star-active.png",  :class=> "img-like" ), "#" %>
      </div>
<!--views -->
      <div class="views">2500
        <a href="#" class="count" data-toggle="tooltip" title="first-tip" data-original-title="23">
        </a>
      </div>
    </div>
  </div>
</li>

app/views/categories/_categories.html.erb
<% all_categories = subject_categories(profile_or_current_subject, {:scope => scope, :limit => 0, :page=> page, :sort_by=> params[:sort_by]||sort_by||"updated_at"}) %>
<% all_categories.each do |category| %>
    <%= render :partial => 'categories/category', :locals => { :category => category } %>
<% end %> 

<script>
  $(document).ready(function(){
    update_pageless_state("categories", <%=all_categories.num_pages%>, <%=all_categories.current_page%>);
  });

</script>

app/views/categories/_categorize_form.html.erb
<span class="fa fa-stack">
  <i class="fa fa-circle  fa fa-stack-base"></i>
  <i class="fa fa-info  fa fa-light"></i>
</span>

<p class="info">
  <%=t('categories.info')%>
</p>

<div class="actions-clone">
  <% categories = subject_categories(current_subject, {:scope => :me, :limit => 0}) %>

  <% if categories.empty? %>
    <a class="btn btn-primary" href="#AddCategory" data-toggle="modal"><%=t('categories.actions.add')%></a>
  <% else %>
    <% categories_array = categories.map { |category| [category.title, category.id] } %>
    
    <% more_options = options_for_select(["-----", [t('categories.actions.add')]], disabled: "-----") %>
    
    <%= select_tag(:category_id, options_for_select(categories_array) + more_options)%>

    <%= form_for categories.first, :remote => true, :class => "form-group", do |f| %>
      <%= f.hidden_field :item_type, :value => item.class.to_s %>
      <%= f.hidden_field :item_id, :value => item.id %>
      <a class="btn btn_cancel"><%=t('cancel')%></a>
      <%= f.submit t('button.save')%>
    <% end %>

    <script>
      $("#category_id").change(function() {
        //If Add a category is selected
        if ($(this).val() == "<%= t('categories.actions.add') %>") {
          //Show Add category partial
          $('#AddCategory').modal();
        } else {
          $(".edit_category").attr("action", "/categories/" + $(this).val());
          $(".edit_category").attr("id", "edit_category_" + $(this).val());
        }
      });
    </script>
  <% end %>
</div>

app/views/categories/_category-add.html.erb
<li class="add-item" href="#AddCategoryHeader" data-toggle="modal">
  <%= link_to new_excursion_path do %>
    <div class="container-img">
        <div class="dummy"></div>
        <div class="element">
          <div class="img-box"><i class="fa fa-plus"></i></div>
        </div>
    </div>
<%# link_to excursion_thumb_for(excursion), excursion, :class => "img-box" %>
<!--INFO excursuion-->
    <div class="caption">
  <!--Title -->
      <div class="action">
        Add New Category  
      </div>
    </div>
  <% end %>
</li>

app/views/categories/_category-favorit.html.erb
<li class="box-item category-favorit">

<!--IMG categories-->
  <div class="category">
    <%= link_to "<i class='fa fa-star'></i>".html_safe, category, :title => category.title %>
  </div>
<!--INFO categories-->
  <div class="caption">
<!--Title -->
    <h6>
      <%= t('excursion.actions.favorite') %>
    </h6>
<!--____________________ -->
    <div class="info-bottom">
      <hr class="soften">
<!--like -->
      <div class="like">    
        <div class="count"><%=category.post_activity.likes.count.to_s%></div>
        <%= link_like(category.post_activity)%>
      </div>
<!--views -->
      <div class="views">
        <%=category.visit_count.to_s%>
        <%=t('follow.views')%>
      </div>
    </div>
  </div>
</li>

app/views/categories/_category.html.erb
<li class="box-item excursion-item">

  <div class="container-img">
      <div class="dummy"></div>
      <div class="element">

        <div class="img-box">
        <!--IMG categories-->
          <%= link_to(category) do %>
            <div class="category">
              <%=category_thumbnail(category)%>            
            </div>
          <% end %>
        </div>

      </div>
  </div>
    
<!--INFO excursuion-->
  <div class="info">
<!--Title -->
    <div class="name">
      <%= link_to category.title, category %>
    </div>
<!--Autor -->
    <div class="author"> 
      <span class="by"><%=t('by')%></span>
      <%= link_to category.author.name, category.author.subject %>
    </div>
    <!--____________________ -->
    <div class="info-bottom">
      <hr class="soften">
      <!--like -->
      <div class="categories_inside">  
        <%=category.property_objects.count.to_s%>
        <%=t('categories.item_inside')%>
    </div>

  </div>
</li>

app/views/categories/_category_fav.html.erb
<li class="box-item resource-item favouritebox">
<!--IMG resource-->
  <div class="container-img">
    <div class="dummy"></div>
    <div class="element resource-center">
      <%= link_to "/categories/favorites" do %>
        <i class="fa fa-star"></i>
      <% end %>
    </div>
  </div>
<!--INFO resource-->
  <div class="caption">
<!--Title -->
    <div class="name">
      <%= link_to t('categories.favorites.title'), "/categories/favorites" %>
    </div>
<!--Autor -->
    <span class="author"> 
      <span class="by"><%=t('by')%></span>
      <%= link_to current_subject.name, current_subject.subject %>
    </span>
  </div>
</li>

app/views/categories/_form.html.erb
<!-- Button to trigger modal --> 
<!-- Modal Categories-->

<div id="AddCategory" class="modal fade" aria-labelledby="AddCategoryLabel">
  <div class="modal-dialog">
    <div class="modal-content">
    
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
        <%= render partial: 'help/help_categorie_new' %>
        <h2 class="modal-title" id="myModalLabel AddCategoryLabel"><%= t('categories.main_title')%></h2>
      </div>

      <div class="modal-body">
        <%= form_for Category.new(:owner_id => Actor.normalize_id(current_user)), :html => {:'data-type' => :json}, :class => "form-group", :remote => remote do |f| %>
          <%= f.hidden_field :owner_id %>
          <!--TITULO-->
          <label><%= t('categories.leyend.title')%></label>
          <%= f.text_field :title, :class => "form-control", :placeholder => t('categories.title_input') %>
          
          <!--DESCRIPCION-->
          <label><%= t('categories.leyend.description')%></label>
          <%= f.text_field :description, :class => "form-control", :placeholder => t('categories.description_input') %>
          <%= f.submit t('categories.save'), :class => "hidden", :id => "saveCategory" %>
        <% end %>
      </div>

      <div class="modal-footer">      
        <!--<a href="#" id="foo" role="button" class="btn btn-primary">Ayuda</a>-->
        <!--<b id="foo" rel="popover">Ayuda </b>-->
        <input type="button" class="btn btn-primary" value="<%= t('categories.save')%>"/>
      </div>
    </div>    
  </div>
</div>

<script>


  $('#AddCategory .new_category').bind('ajax:success', function(evt, data, status, xhr){
    $('#AddCategory').modal('hide');
    window.location.href = "/categories/" + data.id;
  });

  $('#<%=div_id%> .new_category').bind('ajax:error', function(evt, data, status, xhr){
    $("#<%=div_id%> .errors").remove();
    var errors = "There was an unexpected error on the server. Please contact the technical support so they can solve it.";
    if(data.responseJSON!=undefined){
      errors = data.responseJSON.errors;
    }
    if (errors.indexOf("duplicated") != -1) {
      $("#<%=div_id%> .new_category").after("<div class='errors'><%= t('categories.errors.duplicated')%></div>");
    } else {
      $("#<%=div_id%> .new_category").after("<div class='errors'>" + errors + "</div>");
    }
  });

  var saveCategoryButton = $("#<%=div_id%> input[type='submit']");
  var categoryButton = $("#<%=div_id%> input[value=<%= t('categories.save')%>][type='button'][class='btn-primary']");
  $(categoryButton).click(function(event) {
    if ($("#<%=div_id%> input[name='category[title]']").val() == "") {
      $("#<%=div_id%> .errors").remove();
      $("#<%=div_id%> .new_category").after("<div class='errors'><%= t('categories.title_input')%></div>");
    } else {
      $(saveCategoryButton).click();
    }
  });
</script>

app/views/categories/_profile_categories.html.erb
<div id="categories_tab_ready" class="categories">
  <ul class="categories items">
    <% if profile_subject_is_current? %>
      <%= render partial: 'categories/category-add' %>
      <%= render partial: 'categories/category_fav' %>
    <% end %>

    <%= render partial: 'categories/categories', :locals => { :scope => scope, :limit => limit, :page => page, :sort_by=> params[:sort_by]||"updated_at"} %>
    
  </ul>
  
</div>

app/views/categories/_timeline.html.erb
<div class="recomended">
  <ul class="items clearfix">
    <p class="info_action"> Added Category</p>
    <%= render :partial => "categories/category" , :locals => {:category => category}%>
  </ul>
</div>

app/views/categories/favorites.html.erb
<section id="category">
  <div class="category_info">
    <div class="information my_favorites">
      <div class="briefing">
        <header>
          <!--titulo-->
          <h1><i class="fa fa-star"></i> <%= t('categories.favorites.title') %> </h1>
          <!--ayuda-->
          <%= render partial: 'help/help_categories' %>
        </header>   
        <div class="description"> <%= t('categories.favorites.description') %> </div>
      </div>
    </div>
  </div>
  <div class="excursions">
    <ul class="items">
    <%# excursions = subject_excursions(profile_or_current_subject, {:scope => scope, :limit => 0, :page=> page}) %>
      <% items = subject_content current_subject, [Excursion, Picture, Video, Document, Embed, Link], {:scope => :like, :limit=>0} %>
      <% items.each do |item| %>
      <% resources = [Picture, Document, Embed, Link, Video] %>
      <% if resources.include?(item.object.class) %>
        <%= render :partial => 'repositories/resource', :locals => { :resource => item.object } %>
      <% else %>
        <%= render :partial => "#{item.object.class.to_s.tableize}/#{item.object.class.to_s.underscore}", :locals => { item.object.class.to_s.underscore.to_sym => item.object } %>
      <% end %>
    <% end %>
    </ul>
  </div>
<!--   <div id="loader_pagination">
    <div id="pageless-loader" style="text-align:center;width:100%;">
      <div class="msg" style="font-size:2em">
        <%=t('search.loading')%>
      </div>
      <img src="assets/load.gif" alt="loading more results" style="margin:10px auto" />
    </div>
  </div>
  <div id="last_content_shown" style="display:none"> <%=t('search.end')%></div> -->

</section>

app/views/categories/index.html.erb
<section id="categories">
    <ul class="nav nav-tabs">
      <li><h1>categories</h1></li>
      <li class="active"><a href="#tab1" data-toggle="tab">all</a></li>
      <li><a href="#tab2" data-toggle="tab">mine</a></li>
    </ul>
    <div class="tab-content">

      <div class="tab-pane active" id="tab1">
        <%= render partial: 'categories/categories' %>
      </div>

      <div class="tab-pane" id="tab2">
        <%= render partial: 'categories/categories' %>
      </div>
    </div>

</section>

app/views/categories/show.html.erb
<section id="category">
  <div class="category_info">
    <div class="fa fa-box">
      <%=category_thumbnail(@category)%>
    </div>  
    <div class="information">
      <div class="briefing">
        <header>
          <!--titulo-->
          <h1><%= @category.title %></h1>
          <!--ayuda-->
          <%= render partial: 'help/help_categories' %>
        </header>
        <!--descripcion-->
        <div class="description"><%= @category.description %></div>
      
        <div class="btn-group">
          <!--editar-->
          <% if can?(:update, @category) %>
          <%= link_to(raw("<i class='fa fa-edit '></i>")+ t('excursion.actions.edit'), '#', :id => "edit_icon_link", :class =>"btn btn-default") %> 
          <% end %>
          <!--borrar-->
          <% if user_signed_in? and can?(:destroy, @category) %>
          <%= link_to(raw("<i class='fa fa-trash'></i>") + t('excursion.actions.delete') , @category, :method => :delete, :remote => false, :confirm => "Are you sure?", :class =>"action btn btn-default" )%>
          <% end %>
        </div>
      </div>
      <div class="update" style="display:none">
        <%= form_for(@category, :class => "form-group", :url => [@category]) do |f| %>
        <%= f.hidden_field :owner_id %>
        <!--TITULO-->
        <label><%= t('categories.leyend.title')%></label>
        <%= f.text_field :title %>
        <!--DESCRIPCION-->
        <label><%= t('categories.leyend.description')%></label>
        <%= f.text_field :description%>
        <div class="actions">
          <%= f.submit t('categories.save'), :id => "saveCategory", :class=>"btn btn-default" %>
          <%=link_to t('hide'), "#", :id=>"hide_category_form", :class=>"btn btn-primary"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="excursions">
  <ul class="items">
    <%# excursions = subject_excursions(profile_or_current_subject, {:scope => scope, :limit => 0, :page=> page}) %>
    <% @category.property_objects.each do |item| %>
    <% resources = [Picture, Document, Embed, Link, Video] %>
    <% if resources.include?(item.object.class) %>
    <%= render :partial => 'repositories/resource', :locals => { :resource => item.object } %>
    <% else %>
    <%= render :partial => "#{item.object.class.to_s.tableize}/#{item.object.class.to_s.underscore}", :locals => { item.object.class.to_s.underscore.to_sym => item.object } %>
    <% end %>
    <% end %>
  </ul>
</div>


<%= content_for :javascript do %>

  $(document).ready(function() {
    $(".resource").fitText(0.4);

    $(".edit_icon").click(function(){
      alert( "clicked" );
      $(".update").show("slow");
      $(".btn-group").hide("slow");
      $(".information").hide("slow");
    });

    $("#hide_category_form").on("click", function(e){
      $(".update").hide("slow");
      $(".btn-group").show("slow");
      $(".information").show("slow");
    });
  });

<% end %>